### ISSUE TITLE
Android looks like this

### ISSUE THREAD

**Issue by anny1895** [bgryszko/react-native-circular-progress#72]
![screenshot_2017-07-15-13-00-09-732_host exp exponent](https://user-images.githubusercontent.com/29810666/28237461-d37d01c6-695d-11e7-905b-1247f11f4f15.png)
android having issue like this..on ios it worked like a charm?

Help appreciated 😄

**Comment by ishizhen** [comment]
My program like this problem happened

**Comment by ishizhen** [comment]
react native 0.46

**Comment by ishizhen** [comment]
You can modify the content（CircularProgress.js） as follows
methond:

` circlePath(cx, cy, r, startDegree, endDegree) {

    let p = Path();
      p.path.push(0, cx + r, cy);
      p.path.push(4, cx, cy, r, startDegree * Math.PI / 180, endDegree * Math.PI / 180, 1);

    return p;
  }`
and 
` const backgroundPath = this.circlePath(size / 2, size / 2, size / 2 - width / 2, 1, 360);` 
replace
` const backgroundPath = this.circlePath(size / 2, size / 2, size / 2 - width / 2, 0, 360);`


It will show the correct

**Comment by ishizhen** [comment]
You can modify the content（CircularProgress.js） as follows

1. 
methond:
`circlePath(cx, cy, r, startDegree, endDegree) {
let p = Path();
  p.path.push(0, cx + r, cy);
  p.path.push(4, cx, cy, r, startDegree * Math.PI / 180, endDegree * Math.PI / 180, 1);

return p;
};`

and

2. 

`const backgroundPath = this.circlePath(size / 2, size / 2, size / 2 - width / 2, 1, 360);`

replace
`const backgroundPath = this.circlePath(size / 2, size / 2, size / 2 - width / 2, 0, 360);`

It will show the correct

**Comment by uglyspoon** [comment]
@ishizhen it works for me ,thx

**Comment by wuwenbin970731** [comment]
OMG thanks so much!

**Comment by superandrew213** [comment]
@bgryszko will you publish a new version to npm any time soon? This issue has already been fixed in master.

**Comment by chrmcg** [comment]
For those coming here from Google -- until this gets published to npm, you can get the fixed version directly from GitHub by editing your `package.json`:
`"react-native-circular-progress": "bgryszko/react-native-circular-progress#91f15f5a5320c04d645352a629f2478873344f6d"`

**Comment by markusl** [comment]
I believe this is now fixes since https://github.com/bgryszko/react-native-circular-progress/pull/70 is closed

**Comment by JakeRawr** [comment]
Hi, all

Any chance this bug is back with v0.1.2? 
I'm on the latest version, and my circular progress looks like what @anny1895 posted, on android only
